//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public System.Guid Picture_ID { get; set; }
        public byte[] Picture1 { get; set; }
        public Nullable<System.Guid> Challenge_ID { get; set; }
        public Nullable<System.Guid> Objective_ID { get; set; }
        public Nullable<System.Guid> Milestone_ID { get; set; }
    
        public virtual Challenge Challenge { get; set; }
        public virtual Milestone Milestone { get; set; }
        public virtual Objective Objective { get; set; }
    }
}
