//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRating
    {
        public System.Guid Rating_ID { get; set; }
        public string User_ID { get; set; }
        public int Grade { get; set; }
        public System.Guid Objective_ID { get; set; }
    
        public virtual Objective Objective { get; set; }
    }
}
