//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRank
    {
        public System.Guid Rank_ID { get; set; }
        public string User_ID { get; set; }
        public double System_Grade { get; set; }
        public Nullable<double> Users_Grade { get; set; }
        public double Final_Grade { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
